application:
  type: gui

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/university_application?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password

mybatis:
  type-aliases-package: org.group08.universityapplication.pojo
  mapper-locations: classpath:mapper/*.xml

javafx:
  title: University Management System
  stage:
    resizable: false
